### PR TITLE
Addendum

### PR DESCRIPTION
**Pull request by khdcrawford**
@jbloom This now has a full first-draft of the addendum. 

Not sure if we need to get more info about the serum sample or not or if I should split up the methods into a separate section. The actual text is very simple. 

Anyway, not sure if a PR is the best way to make this edit, but it seemed reasonable/I was curious to try it and it seemed easier than sending you a word doc. Feel free to just comment with what changes you think I need to make or edit the word doc.

### CODE REVIEW

**Comment by jbloom** [comment]
@khdusenbury, I made a few small edits / suggestions to the addendum.

Things that still seem like open questions:

 - Will you add this to both _bioRxiv_ and _Viruses_, or just _bioRxiv_. Do you want to contact _Viruses_ and ask if addendum allowed? It could also be an Erratum there, I suppose.

 - It would be nice if this referred to where the new plasmid map could be obtained, as well as the plasmid itself. (Even "Will be deposited...").

  - How will you add to the _bioRxiv_? As an addendum section before the Discussion, then updating the Discussion? Recall for _bioRxiv_ (but probably not for _Viruses_) we can update entire manuscript however we want. It might be nice to maintain some consistency in how this is done, but at least for _bioRxiv_ we also don't want this so buried in the back that people miss it.

**Comment by khdcrawford** [comment]
I just updated the biorxiv manuscript with a (near?) final version of the addendum. 

I tried adding it in before the Discussion, but that actually felt a little weird, so instead I added it as a section between the Discussion and the Methods. I wanted to keep the original paper essentially unchanged, so did not edit the Discussion, but I could if you think I should. Let me know what you think. 

I still have a couple comments about things I struggled to word well, but I think it's close. 

I don't feel super compelled to add to the Viruses manuscript 'cause that feels like a lot of emails, but let me know if you think we should.

**Comment by jbloom** [comment]
@khdusenbury is this ready for me to edit then for re-submission to _bioRxiv_?

**Comment by khdcrawford** [comment]
@jbloom Yep. I would first glance at the structure and if you don't like it, then I can fix that, but otherwise I think it's ready to edit and resubmit.

**Comment by jbloom** [comment]
@khdusenbury, I added some comments into the Word doc, and made a few small edits.

**Comment by khdcrawford** [comment]
@jbloom I think I addressed most of your comments, so I think you could take another look. I haven't done a final edit, but I'm not going to work on this anymore today.

**Pull request closed without merging**
